trigger: ["master"]
pr: ["master"]

pool:
  vmImage: 'ubuntu-latest'
steps:
  - checkout: self
    fetchDepth: 5
  - script: |
      set -e
      curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain stable
      echo "##vso[task.setvariable variable=PATH;]$PATH:$HOME/.cargo/bin"
    displayName: 'Install Rust'
  - script: cargo test
    displayName: "Run unit tests"